### ISSUE TITLE
 PredictionAccuracy module fails to load

### ISSUE THREAD

**Issue by TsimurSh** [TransitTrack/transittrack#49]
The PredictionAccuracy module encounters issues during initialization, preventing it from loading properly. 

@vesavlad how to run or use PredictionAccuracyModule?

**Comment by vesavlad** [comment]
@TsimurSh you can use PredictionAccuracyModule by doing ```@Component``` annotation on it.

**Comment by TsimurSh** [comment]
@vesavlad Yes. It's first what I tried to do. I added to PredictionAccuracy module @Component annotation, but when I realised that the module don't generate a data  I changed dependency injection by deleting annotations @Autowired and adding constructors, but it didn't help as well.

**Comment by vesavlad** [comment]
please share the required data + config so that I can reproduce the problem

**Comment by TsimurSh** [comment]
Here is application.yml: 
 https://drive.google.com/file/d/13kQfUBxlen-yNJcORFektwR9DwUZPIwo/view?usp=drive_link

**Comment by TsimurSh** [comment]
@vesavlad sent via email. Please check your mailbox on outlook

**Comment by vesavlad** [comment]
So just a sidenote:
While using the config looks like the gtfs url does not work
```
2024-12-19T22:21:17.489+02:00 ERROR 7468 --- [   scheduling-1] o.t.core.avl.PollUrlAvlModule            : Error accessing AVL feed using URL=[https://pks.goeuropa.net/api/v1/key/f78a2e9a/agency/1211/command/gtfs-rt/vehiclePositions]. 

java.io.IOException: Server returned HTTP response code: 503 for URL: https://pks.goeuropa.net/api/v1/key/f78a2e9a/agency/1211/command/gtfs-rt/vehiclePositions
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2013)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
	at org.transitclock.core.avl.PollUrlAvlModule.fetchData(PollUrlAvlModule.java:122)
	at org.transitclock.core.avl.PollUrlAvlModule.run(PollUrlAvlModule.java:168)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124)
	at io.micrometer.observation.Observation.observe(Observation.java:499)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124)
	at org.springframework.scheduling.config.Task$OutcomeTrackingRunnable.run(Task.java:83)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

More than that I think there was a missing scheduling for this module.
Please check the bugfix/enable-predaccuracy branch

**Comment by TsimurSh** [comment]
@vesavlad  Sorry, I've forgotten to rerun TC after the reboot server. It - https://github.com/TransitTrack/transittrack/issues/49#issuecomment-2555716510 -  is already active.

**Comment by vesavlad** [comment]
checking it again now, same thing
